-- USER SQL
CREATE USER BPD_MOBILE IDENTIFIED BY "!QAZ2wsx"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE ROLE TO BPD_MOBILE ;
GRANT CREATE TRIGGER TO BPD_MOBILE ;
GRANT ALTER SESSION TO BPD_MOBILE ;
GRANT CREATE MATERIALIZED VIEW TO BPD_MOBILE ;
GRANT CREATE VIEW TO BPD_MOBILE ;
GRANT CREATE SESSION TO BPD_MOBILE ;
GRANT CREATE TABLE TO BPD_MOBILE ;
GRANT CREATE TYPE TO BPD_MOBILE ;
GRANT CREATE PUBLIC SYNONYM TO BPD_MOBILE ;
GRANT CREATE SYNONYM TO BPD_MOBILE ;
GRANT CREATE SEQUENCE TO BPD_MOBILE ;
GRANT CREATE DATABASE LINK TO BPD_MOBILE ;
GRANT UNLIMITED TABLESPACE TO BPD_MOBILE ;
GRANT CREATE PROCEDURE TO BPD_MOBILE ;