--------------------------------------------------------
--  File created - Saturday-October-28-2017   
--------------------------------------------------------
DROP VIEW "BPD_MOBILE"."CHAT_MESSAGES_VIEW";
DROP VIEW "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS_VIEW";
DROP VIEW "BPD_MOBILE"."USER_SUBSCRIPTION_VIEW";
DROP VIEW "BPD_MOBILE"."MSG_ATTACHMENTS_VIEW";
DROP TABLE "BPD_MOBILE"."APP_USERS" cascade constraints;
DROP TABLE "BPD_MOBILE"."ATTACHMENTS" cascade constraints;
DROP TABLE "BPD_MOBILE"."BLOB_TYPE" cascade constraints;
DROP TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" cascade constraints;
DROP TABLE "BPD_MOBILE"."DEVICES" cascade constraints;
DROP TABLE "BPD_MOBILE"."DEVICE_STATUS" cascade constraints;
DROP TABLE "BPD_MOBILE"."DEVICE_TYPE" cascade constraints;
DROP TABLE "BPD_MOBILE"."FI_ATTACHMENTS" cascade constraints;
DROP TABLE "BPD_MOBILE"."MSG_ATTACHMENTS" cascade constraints;
DROP TABLE "BPD_MOBILE"."MESSAGE_TYPES" cascade constraints;
DROP TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" cascade constraints;
DROP TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" cascade constraints;
DROP TABLE "BPD_MOBILE"."USER_DEVICES" cascade constraints;
DROP TABLE "BPD_MOBILE"."USER_STATUS" cascade constraints;
DROP TABLE "BPD_MOBILE"."BLOB_TYPE_CATEGORY" cascade constraints;
DROP TABLE "BPD_MOBILE"."INFORMATION_SOURCE" cascade constraints;
DROP SEQUENCE "BPD_MOBILE"."ATTACHMENT_SEQ";
DROP SEQUENCE "BPD_MOBILE"."BLOB_TYPE_SEQ";
DROP SEQUENCE "BPD_MOBILE"."BLOB_TYPE_CAT_SEQ";
DROP SEQUENCE "BPD_MOBILE"."BPD_MSG_SEQ";
DROP SEQUENCE "BPD_MOBILE"."DEV_SEQ";
DROP SEQUENCE "BPD_MOBILE"."DEV_STATUS_SEQ";
DROP SEQUENCE "BPD_MOBILE"."DEV_TYPE_SEQ";
DROP SEQUENCE "BPD_MOBILE"."MSG_TYPE_SEQ";
DROP SEQUENCE "BPD_MOBILE"."SUB_LOC_SEQ";
DROP SEQUENCE "BPD_MOBILE"."SUB_LOC_TYPE_SEQ";
DROP SEQUENCE "BPD_MOBILE"."TEST_SEQ";
DROP SEQUENCE "BPD_MOBILE"."USER_DEV_SEQ";
DROP SEQUENCE "BPD_MOBILE"."USER_SEQ";
DROP SEQUENCE "BPD_MOBILE"."USER_STATUS_SEQ";
DROP SEQUENCE "BPD_MOBILE"."INFO_SOURCE_SEQ";
DROP PROCEDURE "BPD_MOBILE"."UPDATE_USER_SUB_LOC_INFO";
DROP SYNONYM "PUBLIC"."DUAL";

--------------------------------------------------------
--  DDL for Table APP_USERS
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."APP_USERS" 
   (	"USER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(25 BYTE), 
	"MIDDLE_NAME" VARCHAR2(25 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"USER_STATUS_ID" NUMBER, 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" DATE, 
	"BPD_USER_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."APP_USERS"."USER_ID" IS 'A unique identifier for a user of the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."APP_USERS"."FIRST_NAME" IS 'The first name of a user of the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."APP_USERS"."MIDDLE_NAME" IS 'The middle name of a user of the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."APP_USERS"."LAST_NAME" IS 'The last name of a user of the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."APP_USERS"."USER_STATUS_ID" IS 'A unique identifier the current status of the user of the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."APP_USERS"."ACTIVE_DATE" IS 'The date the user account of the BPD mobile application became active';
   COMMENT ON COLUMN "BPD_MOBILE"."APP_USERS"."INACTIVE_DATE" IS 'The date the user account of the BPD mobile application became inactive';
--------------------------------------------------------
--  DDL for Table ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."ATTACHMENTS" 
   (	"ATTACHMENT_ID" NUMBER, 
	"GANG_MEMBER_ID" NUMBER, 
	"BLOB" BLOB, 
	"BLOB_TYPE_ID" NUMBER, 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"FILE_EXTENSION" VARCHAR2(5 BYTE), 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"SUSPICIOUS_ACTIVITY_REPORT_ID" NUMBER, 
	"FILE_SIZE_IN_BYTES" NUMBER, 
	"INFORMATION_SOURCE_ID" NUMBER, 
	"SMT_LOCATION_ID" NUMBER, 
	"SMT_DESCRIPTION" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(2000 BYTE), 
	"CREATOR_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BLOB") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BLOB_TYPE
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."BLOB_TYPE" 
   (	"BLOB_TYPE_ID" NUMBER, 
	"BLOB_TYPE" VARCHAR2(50 BYTE), 
	"BLOB_TYPE_CATEGORY_ID" NUMBER, 
	"CREATOR_ID" VARCHAR2(30 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Table BLOB_TYPE_CATEGORY
--------------------------------------------------------
 CREATE TABLE "BPD_MOBILE"."BLOB_TYPE_CATEGORY" 
   (	"BLOB_TYPE_CATEGORY_ID" NUMBER(*,0), 
	"BLOB_TYPE_CATEGORY" VARCHAR2(30 BYTE), 
	"CREATOR_ID" VARCHAR2(30 BYTE), 
	"DATE_CREATED" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Table INFORMATION_SOURCE
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."INFORMATION_SOURCE" 
   (	"INFORMATION_SOURCE_ID" NUMBER(*,0), 
	"INFORMATION_SOURCE" VARCHAR2(35 BYTE), 
	"CREATOR_ID" VARCHAR2(30 BYTE), 
	"DATE_CREATED" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;



--------------------------------------------------------
--  DDL for Table BPD_APP_MESSAGES
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" 
   (	"MESSAGE_ID" NUMBER, 
	"MESSAGE_TYPE_ID" NUMBER, 
	"MESSAGE" VARCHAR2(1000 BYTE), 
	"CREATED_BY" NUMBER, 
	"DEVICE_ID" NUMBER, 
	"DATE_CREATED" DATE, 
	"SUBSCRIPTION_LOC_ID" NUMBER, 
        "SECONDARY_LOC_ID" NUMBER, 
	"ADDRESS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."MESSAGE_ID" IS 'A unique identifier for each record in the BPD_APP_MESSAGES table';
   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."MESSAGE_TYPE_ID" IS 'A unique identifier for the type of message';
   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."MESSAGE" IS 'Text value of the message';
   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."CREATED_BY" IS 'A unique identifier for the creator of the message';
   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."DEVICE_ID" IS 'A unique identifier for the device the message was sent';
   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."DATE_CREATED" IS 'The date the message was created';
   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."SUBSCRIPTION_LOC_ID" IS 'A unique identifier representing the location the message was sent';
   COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."ADDRESS_ID" IS 'A unique identifier representing the address of the location';
COMMENT ON COLUMN "BPD_MOBILE"."BPD_APP_MESSAGES"."SECONDARY_LOC_ID" IS 'A unique identifier representing the secondary location of the message';
--------------------------------------------------------
--  DDL for Table DEVICES
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."DEVICES" 
   (	"DEVICE_ID" NUMBER, 
	"DEVICE_NAME" VARCHAR2(50 BYTE), 
	"DEVICE_TYPE_ID" NUMBER, 
	"PHONE_NUMBER" VARCHAR2(12 BYTE), 
	"MAKE" VARCHAR2(50 BYTE), 
	"MODEL" VARCHAR2(50 BYTE), 
	"MAC_ADDRESS" VARCHAR2(30 BYTE), 
	"SERIAL_NUMBER" VARCHAR2(30 BYTE), 
	"DEVICE_STATUS_ID" NUMBER, 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."DEVICE_ID" IS 'A unique identifier for a device used to access the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."DEVICE_NAME" IS 'A short description of the device';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."DEVICE_TYPE_ID" IS 'A unique identifier for the type of the device used to access the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."PHONE_NUMBER" IS 'The phone number associated with the device';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."MAKE" IS 'The make of the device';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."MODEL" IS 'The model number of the device';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."MAC_ADDRESS" IS 'The MAC address of the device';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."SERIAL_NUMBER" IS 'The serial number of the device';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."DEVICE_STATUS_ID" IS 'The unique identifier for the current status of the record';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."ACTIVE_DATE" IS 'The date this device record became active';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICES"."INACTIVE_DATE" IS 'The date this device record became inactive';
--------------------------------------------------------
--  DDL for Table DEVICE_STATUS
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."DEVICE_STATUS" 
   (	"DEVICE_STATUS_ID" NUMBER, 
	"STATUS" VARCHAR2(25 BYTE), 
	"STATUS_DESC" VARCHAR2(100 BYTE), 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_STATUS"."DEVICE_STATUS_ID" IS 'A unique identifier for a device status record';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_STATUS"."STATUS" IS 'A short description of a status record';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_STATUS"."STATUS_DESC" IS 'A long description of a status record';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_STATUS"."ACTIVE_DATE" IS 'The date this status record became active';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_STATUS"."INACTIVE_DATE" IS 'The date this status record became inactive';
--------------------------------------------------------
--  DDL for Table DEVICE_TYPE
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."DEVICE_TYPE" 
   (	"DEVICE_TYPE_ID" NUMBER, 
	"TYPE" VARCHAR2(25 BYTE), 
	"TYPE_DESC" VARCHAR2(100 BYTE), 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_TYPE"."DEVICE_TYPE_ID" IS 'A unique identifier for a device type record';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_TYPE"."TYPE" IS 'A short description of a type record';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_TYPE"."TYPE_DESC" IS 'A long description of a type record';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_TYPE"."ACTIVE_DATE" IS 'The date this type record became active';
   COMMENT ON COLUMN "BPD_MOBILE"."DEVICE_TYPE"."INACTIVE_DATE" IS 'The date this type record became inactive';
--------------------------------------------------------
--  DDL for Table MSG_ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."MSG_ATTACHMENTS" 
   (	"MESSAGE_ID" NUMBER, 
	"ATTACHMENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."MSG_ATTACHMENTS"."MESSAGE_ID" IS 'A unique identifier for a field intelligence message';
   COMMENT ON COLUMN "BPD_MOBILE"."MSG_ATTACHMENTS"."ATTACHMENT_ID" IS 'A unique identifier for an attachment in BPD mobile application system';
--------------------------------------------------------
--  DDL for Table MESSAGE_TYPES
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."MESSAGE_TYPES" 
   (	"MESSAGE_TYPE_ID" NUMBER, 
	"MESSAGE_TYPE" VARCHAR2(20 BYTE), 
	"MESSAGE_TYPE_DESC" VARCHAR2(50 BYTE), 
	"ACTIVE_DATE" DATE, 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."MESSAGE_TYPES"."MESSAGE_TYPE_ID" IS 'A unique idetifier for each row in the MESSAGE_TYPES table';
   COMMENT ON COLUMN "BPD_MOBILE"."MESSAGE_TYPES"."MESSAGE_TYPE" IS 'A short description of the message type';
   COMMENT ON COLUMN "BPD_MOBILE"."MESSAGE_TYPES"."MESSAGE_TYPE_DESC" IS 'A long description of the message type';
--------------------------------------------------------
--  DDL for Table SUBSCRIPTION_LOCATIONS
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" 
   (	"SUBSCRIPTION_LOCATION_TYPE_ID" NUMBER, 
	"SUBSCRIPTION_LOCATION_ID" NUMBER, 
	"SUBSCRIPTION_LOCATION" VARCHAR2(50 BYTE), 
	"SUBSCRIPTION_LOC_DESC" VARCHAR2(100 BYTE), 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS"."SUBSCRIPTION_LOCATION_TYPE_ID" IS 'A unique identifier for a subscription location type record';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS"."SUBSCRIPTION_LOCATION_ID" IS 'A unique identifier for a subscription location record';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS"."SUBSCRIPTION_LOCATION" IS 'A short description of a subscription location record';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS"."SUBSCRIPTION_LOC_DESC" IS 'A long description of a subscription location record';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS"."ACTIVE_DATE" IS 'The date this subscription location record became active';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS"."INACTIVE_DATE" IS 'The date this subscription location record became inactive';
--------------------------------------------------------
--  DDL for Table SUBSCRIPTION_LOCATION_TYPES
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" 
   (	"SUBSCRIPTION_LOCATION_TYPE_ID" NUMBER, 
	"SUBSCRIPTION_LOC_TYPE" VARCHAR2(25 BYTE), 
	"SUBSCRIPTION_LOC_TYPE_DESC" VARCHAR2(100 BYTE), 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES"."SUBSCRIPTION_LOCATION_TYPE_ID" IS 'A unique identifier for a subscription location type record';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES"."SUBSCRIPTION_LOC_TYPE" IS 'A short description of a subscription location type record';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES"."SUBSCRIPTION_LOC_TYPE_DESC" IS 'A long description of a subscription location type record';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES"."ACTIVE_DATE" IS 'The date this subscription location type record became active';
   COMMENT ON COLUMN "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES"."INACTIVE_DATE" IS 'The date this subscription location type record became inactive';
--------------------------------------------------------
--  DDL for Table USER_DEVICES
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."USER_DEVICES" 
   (	"USER_DEVICE_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"DEVICE_ID" NUMBER, 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" DATE, 
	"PRIMARY_SUB_LOCATION_ID" NUMBER, 
	"SECONDARY_SUB_LOCATION_ID" NUMBER, 
	"SUBSCRIPTION_DATE" DATE,
	"LAST_ACCESS_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."USER_DEVICES"."USER_DEVICE_ID" IS 'A unique identifier of the a user device record';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_DEVICES"."USER_ID" IS 'A unique identifier for a user of the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_DEVICES"."DEVICE_ID" IS 'A unique identifier for a device accessing the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_DEVICES"."ACTIVE_DATE" IS 'The date the user began using this device to access the BPD mobile application';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_DEVICES"."INACTIVE_DATE" IS 'The date the user concluded using this device to access the BPD mobile application';
--------------------------------------------------------
--  DDL for Table USER_STATUS
--------------------------------------------------------

  CREATE TABLE "BPD_MOBILE"."USER_STATUS" 
   (	"USER_STATUS_ID" NUMBER, 
	"STATUS" VARCHAR2(25 BYTE), 
	"STATUS_DESC" VARCHAR2(100 BYTE), 
	"ACTIVE_DATE" DATE DEFAULT SYSDATE, 
	"INACTIVE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BPD_MOBILE"."USER_STATUS"."USER_STATUS_ID" IS 'A unique identifier for a status record';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_STATUS"."STATUS" IS 'A short description of a status record';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_STATUS"."STATUS_DESC" IS 'A long description of a status record';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_STATUS"."ACTIVE_DATE" IS 'The date this status record became active';
   COMMENT ON COLUMN "BPD_MOBILE"."USER_STATUS"."INACTIVE_DATE" IS 'The date this status record became inactive';
--------------------------------------------------------
--  DDL for Sequence ATTACHMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."ATTACHMENT_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."ATTACHMENT_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence BLOB_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."BLOB_TYPE_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Sequence BLOB_TYPE_CAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."BLOB_TYPE_CAT_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence BPD_MSG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."BPD_MSG_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."BPD_MSG_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence DEV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."DEV_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."DEV_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence DEV_STATUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."DEV_STATUS_SEQ"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."DEV_STATUS_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence DEV_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."DEV_TYPE_SEQ"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."DEV_TYPE_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence MSG_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."MSG_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."MSG_TYPE_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence SUB_LOC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."SUB_LOC_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."SUB_LOC_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence SUB_LOC_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."SUB_LOC_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."SUB_LOC_TYPE_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence TEST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."TEST_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 1 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_DEV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."USER_DEV_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."USER_DEV_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."USER_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."USER_SEQ" TO PUBLIC;
--------------------------------------------------------
--  DDL for Sequence USER_STATUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."USER_STATUS_SEQ"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT SELECT ON "BPD_MOBILE"."USER_STATUS_SEQ" TO PUBLIC;

--------------------------------------------------------
--  DDL for Sequence INFO_SOURCE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BPD_MOBILE"."INFO_SOURCE_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
  GRANT SELECT ON "BPD_MOBILE"."INFO_SOURCE_SEQ" TO PUBLIC;



--------------------------------------------------------
--  DDL for Index APP_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."APP_USERS_PK" ON "BPD_MOBILE"."APP_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ATTACHMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."ATTACHMENTS_PK" ON "BPD_MOBILE"."ATTACHMENTS" ("ATTACHMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOB_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."BLOB_TYPE_PK" ON "BPD_MOBILE"."BLOB_TYPE" ("BLOB_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index BLOB_TYPE__UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."BLOB_TYPE__UN" ON "BPD_MOBILE"."BLOB_TYPE" ("BLOB_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



--------------------------------------------------------
--  DDL for Index BLOB_TYPE_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."BLOB_TYPE_CATEGORY_PK" ON "BPD_MOBILE"."BLOB_TYPE_CATEGORY" ("BLOB_TYPE_CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index BLOB_TYPE_CAT__UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."BLOB_TYPE_CAT__UN" ON "BPD_MOBILE"."BLOB_TYPE_CATEGORY" ("BLOB_TYPE_CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Index INFORMATION_SOURCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."INFORMATION_SOURCE_PK" ON "BPD_MOBILE"."INFORMATION_SOURCE" ("INFORMATION_SOURCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--------------------------------------------------------
--  DDL for Index INFORMATION_SOURCE__UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."INFORMATION_SOURCE__UN" ON "BPD_MOBILE"."INFORMATION_SOURCE" ("INFORMATION_SOURCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



--------------------------------------------------------
--  DDL for Index BPD_APP_MESSAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."BPD_APP_MESSAGES_PK" ON "BPD_MOBILE"."BPD_APP_MESSAGES" ("MESSAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."DEVICES_PK" ON "BPD_MOBILE"."DEVICES" ("DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEVICE_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."DEVICE_STATUS_PK" ON "BPD_MOBILE"."DEVICE_STATUS" ("DEVICE_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEVICE_TYPE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."DEVICE_TYPE_ID_PK" ON "BPD_MOBILE"."DEVICE_TYPE" ("DEVICE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MESSAGE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."MESSAGE_TYPE_PK" ON "BPD_MOBILE"."MESSAGE_TYPES" ("MESSAGE_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIPTION_LOCATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS_PK" ON "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ("SUBSCRIPTION_LOCATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIPTION_LOCATION_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPE_PK" ON "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" ("SUBSCRIPTION_LOCATION_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUB_LOC_TYPE_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."SUB_LOC_TYPE_UNQ" ON "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ("SUBSCRIPTION_LOCATION_TYPE_ID", "SUBSCRIPTION_LOCATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_DEVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."USER_DEVICES_PK" ON "BPD_MOBILE"."USER_DEVICES" ("USER_DEVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BPD_MOBILE"."USER_STATUS_PK" ON "BPD_MOBILE"."USER_STATUS" ("USER_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ATTACHMENTS_TRIG
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "BPD_MOBILE"."ATTACHMENTS_TRIG"
BEFORE INSERT ON BPD_MOBILE.ATTACHMENTS
FOR EACH ROW
      WHEN (new.ATTACHMENT_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.ATTACHMENT_SEQ.NEXTVAL, TO_DATE(TO_CHAR(SYSDATE, 'MM/DD/YYYY HH24:MI:SS'),'MM/DD/YYYY HH24:MI:SS')
  INTO :new.ATTACHMENT_ID, :NEW.DATE_CREATED
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."ATTACHMENTS_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BLOB_TYPE_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."BLOB_TYPE_TRIG" 
BEFORE INSERT ON BPD_MOBILE.BLOB_TYPE 
FOR EACH ROW
     WHEN (new.BLOB_TYPE_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.BLOB_TYPE_SEQ.NEXTVAL, SYSDATE
  INTO :new.BLOB_TYPE_ID, :new.DATE_CREATED
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."BLOB_TYPE_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BPD_MESSAGES_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."BPD_MESSAGES_TRIG" 
BEFORE INSERT ON BPD_MOBILE.BPD_APP_MESSAGES
FOR EACH ROW
       WHEN (new.MESSAGE_ID IS NULL) BEGIN
    SELECT BPD_MOBILE.BPD_MSG_SEQ.NEXTVAL, TO_DATE(TO_CHAR(SYSDATE, 'MM/DD/YYYY HH24:MI:SS'),'MM/DD/YYYY HH24:MI:SS')
    INTO :new.MESSAGE_ID, :new.DATE_CREATED
    FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."BPD_MESSAGES_TRIG" ENABLE;


--------------------------------------------------------
--  DDL for Trigger DEVICE_STATUS_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."DEVICE_STATUS_TRIG" 
BEFORE INSERT ON BPD_MOBILE.DEVICE_STATUS
FOR EACH ROW
       WHEN (new.DEVICE_STATUS_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.DEV_STATUS_SEQ.NEXTVAL, SYSDATE
  INTO :new.DEVICE_STATUS_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."DEVICE_STATUS_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEVICE_TRIG
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "BPD_MOBILE"."DEVICE_TRIG"
BEFORE INSERT ON BPD_MOBILE.DEVICES
FOR EACH ROW
    DECLARE NUM_OF_ACTIVE_DEVICES NUMBER(5);

  BEGIN
    SELECT COUNT(*) INTO NUM_OF_ACTIVE_DEVICES
    FROM BPD_MOBILE.DEVICES
    WHERE PHONE_NUMBER = :NEW.PHONE_NUMBER
    AND DEVICE_STATUS_ID = 1;
    
    IF NUM_OF_ACTIVE_DEVICES >= 1 AND :NEW.DEVICE_STATUS_ID = 1 THEN
        RAISE_APPLICATION_ERROR (-20001, 'A phone number can only be assigned to one active device');
    END IF;
  
    IF :new.DEVICE_ID IS NULL THEN
        SELECT BPD_MOBILE.DEV_SEQ.NEXTVAL, SYSDATE
        INTO :new.DEVICE_ID, :new.ACTIVE_DATE
        FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "BPD_MOBILE"."DEVICE_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEVICE_TYPE_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."DEVICE_TYPE_TRIG" BEFORE INSERT ON BPD_MOBILE.DEVICE_TYPE
FOR EACH ROW
       WHEN (new.DEVICE_TYPE_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.DEV_TYPE_SEQ.NEXTVAL, SYSDATE
  INTO :new.DEVICE_TYPE_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."DEVICE_TYPE_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MESSAGE_TYPE_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."MESSAGE_TYPE_TRIG" 
BEFORE INSERT ON BPD_MOBILE.MESSAGE_TYPES
FOR EACH ROW
       WHEN (new.MESSAGE_TYPE_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.MSG_TYPE_SEQ.NEXTVAL, SYSDATE
  INTO :new.MESSAGE_TYPE_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."MESSAGE_TYPE_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUB_LOC_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."SUB_LOC_TRIG" 
BEFORE INSERT ON BPD_MOBILE.SUBSCRIPTION_LOCATIONS
FOR EACH ROW
       WHEN (new.SUBSCRIPTION_LOCATION_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.SUB_LOC_SEQ.NEXTVAL, SYSDATE
  INTO :new.SUBSCRIPTION_LOCATION_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."SUB_LOC_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUB_LOC_TYPE_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."SUB_LOC_TYPE_TRIG" 
BEFORE INSERT ON BPD_MOBILE.SUBSCRIPTION_LOCATION_TYPES
FOR EACH ROW
       WHEN (new.SUBSCRIPTION_LOCATION_TYPE_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.SUB_LOC_TYPE_SEQ.NEXTVAL, SYSDATE
  INTO :new.SUBSCRIPTION_LOCATION_TYPE_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."SUB_LOC_TYPE_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_ACCOUNT_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."USER_ACCOUNT_TRIG" 
BEFORE INSERT ON BPD_MOBILE.APP_USERS
FOR EACH ROW
       WHEN (new.USER_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.USER_SEQ.NEXTVAL, SYSDATE
  INTO :new.USER_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."USER_ACCOUNT_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_DEVICE_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."USER_DEVICE_TRIG" 
BEFORE INSERT ON BPD_MOBILE.USER_DEVICES
FOR EACH ROW
       WHEN (new.USER_DEVICE_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.USER_DEV_SEQ.NEXTVAL, SYSDATE
  INTO :new.USER_DEVICE_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."USER_DEVICE_TRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_STATUS_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."USER_STATUS_TRIG" 
BEFORE INSERT ON BPD_MOBILE.USER_STATUS
FOR EACH ROW
       WHEN (new.USER_STATUS_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.USER_STATUS_SEQ.NEXTVAL, SYSDATE
  INTO :new.USER_STATUS_ID, :new.ACTIVE_DATE
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."USER_STATUS_TRIG" ENABLE;


--------------------------------------------------------
--  DDL for Trigger BLOB_TYPE_CAT_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."BLOB_TYPE_CAT_TRIG" 
BEFORE INSERT ON BPD_MOBILE.BLOB_TYPE_CATEGORY
FOR EACH ROW
       WHEN (new.BLOB_TYPE_CATEGORY_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.BLOB_TYPE_CAT_SEQ.NEXTVAL, SYSDATE
  INTO :new.BLOB_TYPE_CATEGORY_ID, :new.DATE_CREATED
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."BLOB_TYPE_CAT_TRIG" ENABLE;


--------------------------------------------------------
--  DDL for Trigger INFORMATION_SOURCE_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BPD_MOBILE"."INFORMATION_SOURCE_TRIG" 
BEFORE INSERT ON BPD_MOBILE.INFORMATION_SOURCE
FOR EACH ROW
       WHEN (new.INFORMATION_SOURCE_ID IS NULL) BEGIN
  SELECT BPD_MOBILE.INFO_SOURCE_SEQ.NEXTVAL, SYSDATE
  INTO :new.INFORMATION_SOURCE_ID, :new.DATE_CREATED
  FROM DUAL;
END;
/
ALTER TRIGGER "BPD_MOBILE"."INFORMATION_SOURCE_TRIG" ENABLE;


--------------------------------------------------------
--  DDL for Procedure UPDATE_USER_SUB_LOC_INFO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "BPD_MOBILE"."UPDATE_USER_SUB_LOC_INFO" 
(
  IN_USER_ID IN NUMBER 
, IN_DEVICE_ID IN NUMBER 
, IN_PRIMARY_LOCATION_ID IN NUMBER 
, IN_SECONDARY_LOCATION_ID IN NUMBER 
) AS 
BEGIN
  UPDATE BPD_MOBILE.USER_DEVICES
  SET PRIMARY_SUB_LOCATION_ID = NVL(IN_PRIMARY_LOCATION_ID,NULL),
  SECONDARY_SUB_LOCATION_ID = NVL(IN_SECONDARY_LOCATION_ID,NULL),
  SUBSCRIPTION_DATE = TO_DATE(TO_CHAR(SYSDATE, 'MM/DD/YYYY HH24:MI:SS'),'MM/DD/YYYY HH24:MI:SS')
  WHERE USER_ID = IN_USER_ID
  AND DEVICE_ID = IN_DEVICE_ID;
END UPDATE_USER_SUB_LOC_INFO;

/
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
--------------------------------------------------------
--  Constraints for Table APP_USERS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."APP_USERS" ADD CONSTRAINT "APP_USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."APP_USERS" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."APP_USERS" MODIFY ("USER_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."APP_USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."APP_USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."APP_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."APP_USERS" MODIFY ("BPD_USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."ATTACHMENTS" ADD CONSTRAINT "ATTACHMENTS_PK" PRIMARY KEY ("ATTACHMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."ATTACHMENTS" MODIFY ("CREATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."ATTACHMENTS" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."ATTACHMENTS" MODIFY ("BLOB_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."ATTACHMENTS" MODIFY ("BLOB" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."ATTACHMENTS" MODIFY ("ATTACHMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOB_TYPE
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."BLOB_TYPE" ADD CONSTRAINT "BLOB_TYPE_PK" PRIMARY KEY ("BLOB_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."BLOB_TYPE" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BLOB_TYPE" MODIFY ("BLOB_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BLOB_TYPE" MODIFY ("BLOB_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPD_APP_MESSAGES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" ADD CONSTRAINT "BPD_APP_MESSAGES_PK" PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" MODIFY ("SUBSCRIPTION_LOC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" MODIFY ("MESSAGE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVICES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."DEVICES" ADD CONSTRAINT "DEVICES_PK" PRIMARY KEY ("DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("DEVICE_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("MAKE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("DEVICE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("DEVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICES" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVICE_STATUS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."DEVICE_STATUS" ADD CONSTRAINT "DEVICE_STATUS_PK" PRIMARY KEY ("DEVICE_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."DEVICE_STATUS" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICE_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICE_STATUS" MODIFY ("DEVICE_STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVICE_TYPE
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."DEVICE_TYPE" ADD CONSTRAINT "DEVICE_TYPE_ID_PK" PRIMARY KEY ("DEVICE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."DEVICE_TYPE" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICE_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."DEVICE_TYPE" MODIFY ("DEVICE_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MSG_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."MSG_ATTACHMENTS" MODIFY ("ATTACHMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."MSG_ATTACHMENTS" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESSAGE_TYPES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."MESSAGE_TYPES" ADD CONSTRAINT "MESSAGE_TYPE_PK" PRIMARY KEY ("MESSAGE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."MESSAGE_TYPES" MODIFY ("MESSAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."MESSAGE_TYPES" MODIFY ("MESSAGE_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCRIPTION_LOCATIONS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ADD CONSTRAINT "SUB_LOC_TYPE_UNQ" UNIQUE ("SUBSCRIPTION_LOCATION_TYPE_ID", "SUBSCRIPTION_LOCATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ADD CONSTRAINT "SUBSCRIPTION_LOCATIONS_PK" PRIMARY KEY ("SUBSCRIPTION_LOCATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" MODIFY ("SUBSCRIPTION_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" MODIFY ("SUBSCRIPTION_LOCATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" MODIFY ("SUBSCRIPTION_LOCATION_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCRIPTION_LOCATION_TYPES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" ADD CONSTRAINT "SUBSCRIPTION_LOCATION_TYPE_PK" PRIMARY KEY ("SUBSCRIPTION_LOCATION_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" MODIFY ("SUBSCRIPTION_LOC_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" MODIFY ("SUBSCRIPTION_LOCATION_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_DEVICES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" ADD CONSTRAINT "USER_DEVICES_PK" PRIMARY KEY ("USER_DEVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" MODIFY ("USER_DEVICE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_STATUS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."USER_STATUS" ADD CONSTRAINT "USER_STATUS_PK" PRIMARY KEY ("USER_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BPD_MOBILE"."USER_STATUS" MODIFY ("ACTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."USER_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPD_MOBILE"."USER_STATUS" MODIFY ("USER_STATUS_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Ref Constraints for Table BPD_APP_MESSAGES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" ADD CONSTRAINT "PRIM_LOC_FK" FOREIGN KEY ("SUBSCRIPTION_LOC_ID")
	  REFERENCES "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ("SUBSCRIPTION_LOCATION_ID") ENABLE;
ALTER TABLE "BPD_MOBILE"."BPD_APP_MESSAGES" ADD CONSTRAINT "SEC_LOC_FK" FOREIGN KEY ("SECONDARY_LOC_ID")
	  REFERENCES "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ("SUBSCRIPTION_LOCATION_ID") ENABLE;


--------------------------------------------------------
--  Ref Constraints for Table APP_USERS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."APP_USERS" ADD CONSTRAINT "USER_STATUS_FK" FOREIGN KEY ("USER_STATUS_ID")
	  REFERENCES "BPD_MOBILE"."USER_STATUS" ("USER_STATUS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."ATTACHMENTS" ADD CONSTRAINT "BLOB_TYPE_ID_FK" FOREIGN KEY ("BLOB_TYPE_ID")
	  REFERENCES "BPD_MOBILE"."BLOB_TYPE" ("BLOB_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEVICES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."DEVICES" ADD CONSTRAINT "DEV_STATUS_FK" FOREIGN KEY ("DEVICE_STATUS_ID")
	  REFERENCES "BPD_MOBILE"."DEVICE_STATUS" ("DEVICE_STATUS_ID") ENABLE;
  ALTER TABLE "BPD_MOBILE"."DEVICES" ADD CONSTRAINT "DEV_TYPE_FK" FOREIGN KEY ("DEVICE_TYPE_ID")
	  REFERENCES "BPD_MOBILE"."DEVICE_TYPE" ("DEVICE_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MSG_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."MSG_ATTACHMENTS" ADD CONSTRAINT "FI_ATT_ATT_ID_FK" FOREIGN KEY ("ATTACHMENT_ID")
	  REFERENCES "BPD_MOBILE"."ATTACHMENTS" ("ATTACHMENT_ID") ENABLE;
  ALTER TABLE "BPD_MOBILE"."MSG_ATTACHMENTS" ADD CONSTRAINT "FI_ATT_MSG_ID_FK" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "BPD_MOBILE"."BPD_APP_MESSAGES" ("MESSAGE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCRIPTION_LOCATIONS
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ADD CONSTRAINT "SUB_LOC_TYPE_FK" FOREIGN KEY ("SUBSCRIPTION_LOCATION_TYPE_ID")
	  REFERENCES "BPD_MOBILE"."SUBSCRIPTION_LOCATION_TYPES" ("SUBSCRIPTION_LOCATION_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_DEVICES
--------------------------------------------------------

  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" ADD CONSTRAINT "DEVICE_ID_FK" FOREIGN KEY ("DEVICE_ID")
	  REFERENCES "BPD_MOBILE"."DEVICES" ("DEVICE_ID") ENABLE;
  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" ADD CONSTRAINT "PRIM_SUB_LOC_ID_FK" FOREIGN KEY ("PRIMARY_SUB_LOCATION_ID")
	  REFERENCES "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ("SUBSCRIPTION_LOCATION_ID") ENABLE;
  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" ADD CONSTRAINT "SEC_SUB_LOC_ID_FK" FOREIGN KEY ("SECONDARY_SUB_LOCATION_ID")
	  REFERENCES "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS" ("SUBSCRIPTION_LOCATION_ID") ENABLE;
  ALTER TABLE "BPD_MOBILE"."USER_DEVICES" ADD CONSTRAINT "USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "BPD_MOBILE"."APP_USERS" ("USER_ID") ENABLE;


--------------------------------------------------------
--  DDL for View CHAT_MESSAGES_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BPD_MOBILE"."CHAT_MESSAGES_VIEW" ("MESSAGE_TYPE_ID", "MESSAGE_TYPE_DESC", "MESSAGE", "USER_ID", "USER_NAME", "LAST_NAME", "FIRST_NAME", "DEVICE_ID", "DEVICE_NAME", "DATE_CREATED", "TIME_MESSAGE_CREATED", "MESSAGE_LOCATION_ID", "MESSAGE_LOCATION", "SECONDARY_LOCATION_ID", "SECONDARY_MESSAGE_LOCATION") AS 
  SELECT BPD.MESSAGE_TYPE_ID, M.MESSAGE_TYPE_DESC, BPD.MESSAGE, U.USER_ID, U.BPD_USER_ID, U.LAST_NAME, U.FIRST_NAME, D.DEVICE_ID, D.DEVICE_NAME,
BPD.DATE_CREATED, TO_CHAR(BPD.DATE_CREATED, 'HH24:MI:SS') AS TIME_MESSAGE_CREATED,
BPD.SUBSCRIPTION_LOC_ID AS MESSAGE_LOCATION_ID, SL.SUBSCRIPTION_LOC_DESC AS MESSAGE_LOCATION,
BPD.SECONDARY_LOC_ID AS SECONDARY_LOCATION_ID,
(SELECT SUBSCRIPTION_LOC_DESC FROM SUBSCRIPTION_LOCATIONS WHERE SUBSCRIPTION_LOCATION_ID = BPD.SECONDARY_LOC_ID) AS SEC_MESSAGE_LOCATION
FROM BPD_APP_MESSAGES BPD
INNER JOIN APP_USERS U
ON BPD.CREATED_BY = U.USER_ID
INNER JOIN DEVICES D
ON BPD.DEVICE_ID = D.DEVICE_ID
INNER JOIN SUBSCRIPTION_LOCATIONS SL
ON SL.SUBSCRIPTION_LOCATION_ID = BPD.SUBSCRIPTION_LOC_ID
INNER JOIN MESSAGE_TYPES M
ON BPD.MESSAGE_TYPE_ID = M.MESSAGE_TYPE_ID
ORDER BY BPD.DATE_CREATED;
--------------------------------------------------------
--  DDL for View SUBSCRIPTION_LOCATIONS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BPD_MOBILE"."SUBSCRIPTION_LOCATIONS_VIEW" ("SUBSCRIPTION_LOCATION_TYPE", "SUBSCRIPTION_LOCATION_ID", "SUBSCRIPTION_LOCATION_DESC") AS 
  SELECT SLT.SUBSCRIPTION_LOC_TYPE_DESC AS SUBSCRIPTION_LOCATION_TYPE, 
SL.SUBSCRIPTION_LOCATION_ID AS SUBSCRIPTION_LOCATION_ID, 
SL.SUBSCRIPTION_LOC_DESC AS SUBSCRIPTION_LOCATION_DESC
FROM SUBSCRIPTION_LOCATION_TYPES SLT
INNER JOIN SUBSCRIPTION_LOCATIONS SL
ON SLT.SUBSCRIPTION_LOCATION_TYPE_ID = SL.SUBSCRIPTION_LOCATION_TYPE_ID
WHERE TO_DATE(TO_CHAR(SL.ACTIVE_DATE,'MM/DD/YYYY'),'MM/DD/YYYY') <= TO_DATE(TO_CHAR(SYSDATE,'MM/DD/YYYY'),'MM/DD/YYYY')
AND (SL.INACTIVE_DATE IS NULL OR SYSDATE > TO_DATE(TO_CHAR(SL.INACTIVE_DATE,'MM/DD/YYYY'),'MM/DD/YYYY'))
;
--------------------------------------------------------
--  DDL for View USER_SUBSCRIPTION_VIEW
--------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "BPD_MOBILE"."USER_SUBSCRIPTION_VIEW" ("USER_ID", "USER_NAME", "FIRST_NAME", "LAST_NAME", "DEVICE_ID", "DEVICE_NAME", "PHONE_NUMBER", "PRIMARY_SUB_LOC_ID", "SECONDARY_SUB_LOC_ID", "PRIMARY_SUB_LOCATION", "SECONDARY_SUB_LOCATION", "SUBSCRIPTION_DATE", "TIME_SUBSCRIBED") AS 
  SELECT  UD.USER_ID, U.BPD_USER_ID, U.FIRST_NAME, U.LAST_NAME,  UD.DEVICE_ID, D.DEVICE_NAME, D.PHONE_NUMBER,
(SELECT SUBSCRIPTION_LOCATION_ID FROM SUBSCRIPTION_LOCATIONS WHERE SUBSCRIPTION_LOCATION_ID = UD.PRIMARY_SUB_LOCATION_ID) AS PRIMARY_SUBSCRIPTION_LOC_ID,
(SELECT SUBSCRIPTION_LOCATION_ID FROM SUBSCRIPTION_LOCATIONS WHERE SUBSCRIPTION_LOCATION_ID = UD.SECONDARY_SUB_LOCATION_ID) AS SECONDARY_SUBSCIPTION_LOC_ID,
(SELECT SUBSCRIPTION_LOC_DESC FROM SUBSCRIPTION_LOCATIONS WHERE SUBSCRIPTION_LOCATION_ID = UD.PRIMARY_SUB_LOCATION_ID) AS PRIMARY_SUBSCRIPTION_LOCATION,
(SELECT SUBSCRIPTION_LOC_DESC FROM SUBSCRIPTION_LOCATIONS WHERE SUBSCRIPTION_LOCATION_ID = UD.SECONDARY_SUB_LOCATION_ID) AS SECONDARY_SUBSCIPTION_LOCATION,
UD.SUBSCRIPTION_DATE, TO_CHAR(UD.SUBSCRIPTION_DATE, 'HH24:MI:SS') AS TIME_SUBSCRIBED
FROM APP_USERS U
INNER JOIN USER_DEVICES UD
ON U.USER_ID = UD.USER_ID
INNER JOIN DEVICES D
ON D.DEVICE_ID = UD.DEVICE_ID
WHERE TO_DATE(TO_CHAR(UD.ACTIVE_DATE,'MM/DD/YYYY'),'MM/DD/YYYY') <= TO_DATE(TO_CHAR(SYSDATE,'MM/DD/YYYY'),'MM/DD/YYYY')
;

--------------------------------------------------------
--  DDL for View USER_DEVICES_VIEW
--------------------------------------------------------

 CREATE OR REPLACE FORCE VIEW "BPD_MOBILE"."USER_DEVICES_VIEW" ("USER_ID", "USER_NAME", "FIRST_NAME", "LAST_NAME", "TYPE", "DEVICE_ID", "DEVICE_NAME", "PHONE_NUMBER", "MAKE", "MODEL", "MAC_ADDRESS", "STATUS") AS 
  SELECT  UD.USER_ID, U.BPD_USER_ID, U.FIRST_NAME, U.LAST_NAME, DT.TYPE, UD.DEVICE_ID, D.DEVICE_NAME, D.PHONE_NUMBER, D.MAKE, D.MODEL, D.MAC_ADDRESS,
DS.STATUS
FROM APP_USERS U
INNER JOIN USER_DEVICES UD
ON U.USER_ID = UD.USER_ID
INNER JOIN DEVICES D
ON D.DEVICE_ID = UD.DEVICE_ID
INNER JOIN DEVICE_STATUS DS
ON D.DEVICE_STATUS_ID = DS.DEVICE_STATUS_ID
INNER JOIN DEVICE_TYPE DT
ON D.DEVICE_TYPE_ID = DT.DEVICE_TYPE_ID
WHERE TO_DATE(TO_CHAR(UD.ACTIVE_DATE,'MM/DD/YYYY'),'MM/DD/YYYY')  <= TO_DATE(TO_CHAR(SYSDATE,'MM/DD/YYYY'),'MM/DD/YYYY')
AND (UD.INACTIVE_DATE IS NULL OR SYSDATE > TO_DATE(TO_CHAR(UD.INACTIVE_DATE,'MM/DD/YYYY'),'MM/DD/YYYY'));


--------------------------------------------------------
--  DDL for View MSG_ATTACHMENTS_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BPD_MOBILE"."MSG_ATTACHMENTS_VIEW" ("MESSAGE_ID", "ATTACHMENT_ID", "BLOB", "BLOB_TYPE", "FILE_EXTENSION", "FILE_NAME", "DATE_CREATED") AS 
  SELECT MA.MESSAGE_ID, A.ATTACHMENT_ID, A.BLOB, BT.BLOB_TYPE, A.FILE_EXTENSION, A.FILE_NAME, A.DATE_CREATED
FROM ATTACHMENTS A
INNER JOIN BLOB_TYPE BT
ON A.BLOB_TYPE_ID = BT.BLOB_TYPE_ID
INNER JOIN MSG_ATTACHMENTS MA
ON A.ATTACHMENT_ID = MA.ATTACHMENT_ID
;

